
CREATE DATABASE IF NOT EXISTS Ident;
use Ident;

CREATE TABLE IF NOT EXISTS users (
    
    id INT(10) unsigned NOT NULL AUTO_INCREMENT,
    names VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
    surnames VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id),
    INDEX(id)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;
DESCRIBE users;

CREATE TABLE IF NOT EXISTS passengers (
    
    id INT(10) unsigned NOT NULL AUTO_INCREMENT,
    id_user INT(10) unsigned NOT NULL,
    birthdate DATETIME NOT NULL,
    email VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
    phone INT(16) unsigned NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAM NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (id_user)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;

DESCRIBE passengers;

CREATE TABLE IF NOT EXISTS crew (
    
    id INT(10) unsigned NOT NULL AUTO_INCREMENT,
    id_user INT(10) unsigned NOT NULL,
    dependence VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    INDEX(id),
    PRIMARY KEY(id),
    FOREIGN KEY (id_user)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;

DESCRIBE crew;

ALTER USER 'mysql'@'%' IDENTIFIED WITH mysql_native_password BY '1234';
FLUSH PRIVILEGES;